spring.application.name=telegram-bot-spring-auphonic
telegram.bot.token=8839098228:AAHGb1lLi9_gApRsxK6b1buLUT7_YY810g8
auphonic.api.key=GWv44VoUru4SD510YAcDzmrbkWbMG84K
auphonic.preset=zi6kprbo39HbcTA2va9xyZ